### ISSUE TITLE
App Hungs when close embedded navigator on Android (Video example)

### ISSUE THREAD

**Issue by rgarciadelongoria** [capacitor-community/facebook-login#132]
**Describe the bug**
When close embedded navigator App hangs until press native back button.

**To Reproduce**
1. Call to `await FacebookLogin.login({ permissions: FACEBOOK_PERMISSIONS });`
2. Wait for navigator open
3. Close embedded navigator
4. App hungs
5. Press back button
6. App runs

In Emulator or Real device, Android +30 or others.

![ezgif-3-4ddccb86a0](https://user-images.githubusercontent.com/84543810/234791281-f5cf17d9-8ea3-4d4f-88fb-41cf5f60b47e.gif)

Thanks for helping!

**Comment by rgarciadelongoria** [comment]
Fix this updating facebook-android-sdk version to 16.0.0

**Comment by rgarciadelongoria** [comment]
Change merged in versión 5.0.0

I update my personal project to this versión and the bug has gone.

**Comment by juanico18** [comment]
@rdlabo @stewones We have a problem with plugin version for capacitor 4. 
Login is not returning any response when using com.facebook.android:facebook-login:14.1.0 in Android.
The fix is present here: https://github.com/facebook/facebook-android-sdk/blob/main/CHANGELOG.md#1411

Can you release a new version for capacitor 4 that updates the android sdk?

Is a bit hard to find the problem because login process on facebook works well but does not return anything.
Just happen if login is done by web from Android because the user has not the Facebook app installed.
